print("ra aris am gamosaxulebis pasuxi")
print("(1 and 0) or (1 and 1) and (0 or 0)")
print("1 is true")
print("0 is false")
print("1 and 0 = 0")
print("1 and 1 = 1")
print("0 or 0 = 0")
print("0 or 1 = 1")
print("1 and 0 = 0")
print("0 =  false")